paths:
  /organisation:
    post:
      summary: Create or update organisation data
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: The user to create.
          schema:
            $ref: '#/definitions/User'     # <----------
        responses:
          200:
            description: OK
      definitions:
        User: # <----------
          type: object
          required:
            - userName
          properties:
            userName:
              type: string
            firstName:
              type: string
            lastName:
              type: string